#ifndef CONFIG_H
#define CONFIG_H

#include "file_utils.h"

#define LIBPOSTAL_DATA_DIR ".." PATH_SEPARATOR "data"

#define LIBPOSTAL_DICTIONARIES_DIR LIBPOSTAL_DATA_DIR PATH_SEPARATOR "dictionaries"
#define LIBPOSTAL_GEODB_DIR LIBPOSTAL_DATA_DIR PATH_SEPARATOR "geodb"

#endif