enum gn_postal_fields {
    GN_POSTAL_CODE=0,
    GN_POSTAL_COUNTRY_CODE=1,
    GN_POSTAL_COUNTRY_GEONAMES_ID=2,
    GN_POSTAL_COUNTRY_POPULATION=3,
    GN_POSTAL_CONTAINING_GEONAME_ID=4,
    GN_POSTAL_ADMIN1_IDS=5,
    GN_POSTAL_ADMIN2_IDS=6,
    GN_POSTAL_ADMIN3_IDS=7,
    NUM_POSTAL_FIELDS
};
