name: add to project senzing github organization

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  repository-projects: write

jobs:
  add-to-project:
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project.yaml@v2
    with:
      classic: false
      project-number: ${{ vars.SENZING_GITHUB_ORGANIZATION_PROJECT }}
      org: ${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}

  slack-notification:
    needs: [add-to-project]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.add-to-project.outputs.job-status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.add-to-project.outputs.job-status }}
