name: add to project senzing github organization dependabot

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  add-to-project-dependabot:
    permissions:
      repository-projects: write
    secrets:
      PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project-dependabot.yaml@v4
    with:
      project: ${{ vars.SENZING_GITHUB_ORGANIZATION_PROJECT }}
